# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parser.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\x06parser\"\'\n\x0ePredictRequest\x12\x15\n\roriginal_text\x18\x01 \x01(\t\"#\n\x0fPredictResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t2L\n\x0cProtoService\x12<\n\x07Predict\x12\x16.parser.PredictRequest\x1a\x17.parser.PredictResponse\"\x00\x42\tZ\x07/parserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007/parser'
  _globals['_PREDICTREQUEST']._serialized_start=24
  _globals['_PREDICTREQUEST']._serialized_end=63
  _globals['_PREDICTRESPONSE']._serialized_start=65
  _globals['_PREDICTRESPONSE']._serialized_end=100
  _globals['_PROTOSERVICE']._serialized_start=102
  _globals['_PROTOSERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
